services:
  api:
    build:
      context: ./nestjs-demo
      dockerfile: Dockerfile
    container_name: focusbear-nestjs
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: focusbear_dev
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    container_name: focusbear-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: focusbear_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: focusbear-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  postgres_data: